coder2hacker/Explore-open-source

Jassi10000.json
=> Added my data

gaurav24072002.json
=> Added gaurav24072002.json

nehasoni05.json
=> Neha Soni-new contributor

ArrayListDemo.java, palindrome.c, patterns.c, two_cities.c
Program to check Palindrome in C
=> Program to check Palindrome in C

reverse_4digit.c, total_price.c
program of GST Calculator on Price in c
=> program of GST Calculator on Price in c

factorial.c
Program to Find Factorial in C
=> Program to Find Factorial in c

size_primary_data_type.c
Program to find Size of Primitive data type in c
=> Program to find Size of Primitive data type in c

Disk Space Analysis.cpp
Problem Statement -:  You are given an array, You have to choose a contiguous subarray of length ‘k’, and find the minimum of that segment, return the maximum of those minimums.
Sample input 0 
1 →  Length of segment x =1
5 →  size of space n = 5
1 → space = [ 1,2,3,1,2]
2 
3 
1 
2 
Sample output
3
Explanation
The subarrays of size x = 1 are [1],[2],[3],[1], and [2],Because each subarray only contains 1 element, each value is minimal with respect to the subarray it is in. The maximum of these values is 3. Therefore, the answer is 3
=> Disk Space Analysis

superArrayOfObjects.js
Added solution using filter and includes
=> Added solution using filter and includes

godsakani.json
- Added personal content in json file format
=> feat: Added personal content

python program/Caesar_cipher.py
A encryption decryption algorithm
=> Caesar_cipher.py

java program/Hill_cipher.java
It is a method of encrypttion and decryption i.e. converting plain text to cipher text
=> Hill_Cipher.java

pancake-sorting.cpp
Added a pancake sorting approach in cpp, please merge this and give it a hacktoberfest accepted label to make it a succesful PR, Thanks
=> Created pancake-sorting.cpp

create a telegram bot using Python
create a telegram bot using Python
=> Create create a telegram bot using Python

Password Generator using Python
Password Generator using Python
=> Create Password Generator using Python

Method Parameters in C#
Created Method Parameters in C#
=> Create Method Parameters in C#

SMART in Scrum
Abbreviation Of SMART in Scrum
=> Create SMART in Scrum

java program/OctalToDecimal.java
=> Created Convert OctalToDecimal.java

python program/Selection sort_Adarsh_Mohanty
This is a python program for selection sort.
=> Create Selection sort_Adarsh_Mohanty

Longest_mountain_inArray_Leetcde_cpp.txt, candy_problem_leetcode_cpp.txt
hard level candy problem solution of leetcode
=> a cpp program

ShortestUnsortedContinuosSubarray_leetcode_cpp.txt
ShortestUnsortedContinuosSubarray_leetcode_cpp solution
=> ShortestUnsortedContinuosSubarray_leetcode_cpp

Product_array_Except_self.txt
=> Product_array_Except_self

python program/turtle race.py
turtle race game using python
please accept the changes
=> turtle race

compatibiltyTest.js
It is a simple program for generating a random number using javascript. The range of the number is 1-100 and is represented as the compatibility percentage between two people (friends/classmates/ strangers). The program will take the names as input and return the <random_num_generated> % as the output.
=> CompatibiltyTest.js

ChadGichuki.json
Thank you for the chance to practice contributing to open source
=> Added new json file as per contributing sample

Dvd1234.java
[Hactoberfest 2022] Created a code snippet that computes the pairs in an array having the sum equal to a given number. Have also mentioned the space and time complexities.
=> Added Code to compute pairs having a given sum

BST.cpp, Project_1.html, cssProject.css
Added HTML files and CSS files under form submission. 
Accept this under Hacktoberfest 2022 .
=> Added Form

java program/Bubble_sort.java
=> bubble sort code in java

java program/binary_search.java
=> binary search in java

python program/fibonaccifunction.py
Write a python code to find the fibonacci series of the given number
=> Fibonacci Series

styleCss.css, webpage.html
Added Login/SignUp landing page using HTML and CSS .
Merge this under hacktoberfest 2022 and please provide labels.
=> Login/SignUp landing page 

Floyd_Warshall_Algorithm.cpp
Added Floyd_Warshall_Algorithm in C++
=> Floyd_Warshall_Algorithm.cpp

clock.css, clock.html, towerOfHanoi.cpp
Added Tower of Hanoi solution using recursion.
Merge this under hacktoberfest 2022 and please provide the labels.
=> Tower Of Hanoi using recursion

kruskal's.cpp
=> kruskal algo

kadane's algorithm
=> kadane's algorithm

cal.html
calculator using html,css and javascript
=> Calculator

mi-clone
=> Add code for binary search

python program/affine_chiper.py
Hi, I'm adding cryptography method called Affine Chiper
=> adding affine chiper

NLP using Python.ipynb, java program/Inheritance_working/Bicycle.java, java program/Inheritance_working/Bike.java, java program/Inheritance_working/Car.java, java program/Inheritance_working/Main.java, java program/Inheritance_working/Vehicle.java
NLP with Python file . Kindly merge it to main branch
=> Changes made and Added new File

python program/unit_convert.py
A Simple program to convert values between Metric Units. Might add more types in the future.
=> Unit Converter

4 Sum.cpp
**Created 4 sum.cpp using greedy approach**
=> Created 4 sum.cpp using greedy approach

python program/Morse_code_translator.py
Hey ! I have added Morse code translator. Please merge it in your repository with hacktoberfest-accepted label.
=> Morse code translator

silverBarProblem.cpp
=> Famous Silver bar problem added

Palindrome Partitioning.cpp
**please merge this and give it a label of hacktoberfest accepted**
=> Create Palindrome Partitioning.cpp

DS_project LRU part2
=> Create DS_project LRU part2

DS_project_LRU part3
Css file uploaded..... download all files and make it run on any browser
=> Create DS_project_LRU part3

DS_project_notepad part1
=> Create DS_project_notepad part1

ThreadedBST.cpp
=> Thread BST added

java program/ReplaceWord.java
=> ReplaceWord.java

Linked List Basics/Merge two sorted linked lists.cpp, Linked List Basics/Modify linked list.cpp
I added program to merge two sorted linked lists in C++.
=> Create Merge two sorted linked lists.cpp

Linked List Basics/Rotate a Linked List.cpp, Linked List Basics/linked list of strings forms a palindrome.cpp
Program for linked list of strings forms a palindrome
=> Added linked list of strings forms a palindrome

find factorial using recursion.py
this will automatically merged
=> this will automatically merged

Linked List Basics/Reverse a linked list.cpp
Added Program for Reverse Linked List.
=> Create Reverse a linked list.cpp

Linked List Basics/Absolute List Sorting.cpp, Linked List Basics/Compare two linked lists.cpp, Linked List Basics/Count nodes of linked list.cpp, Linked List Basics/Delete node in Doubly Linked List.cpp, Linked List Basics/Find length of loop.cpp
Hello Author, 
I have created a C++ program to find the length of the loop to solve this issue #378.
Can you plz accept this request...?
=> Find length of loop.cpp

Determine if Two Trees are Identical.cpp, Linked List Basics/Delete Alternate Nodes.cpp
I have created this issue, plz assign it to me...
=> Determine if Two Trees are Identical.cpp

tower_of_hanoi_recursion.cpp
The code is added to the repo.
Please merge my code with hacktoberfest label.
Thank you
=> Tower of hanoi recursion 

Binary_search.java
Added a java code for binary search
=> Java code for binary search

area.c, big.c, decimal.c, hft.c, hgv.c, swap.c
=> Added C Programs

Frequency.java
Hello I have contributed a Java Program to find the frequency of each element in the array. 
Please accept my PR.
=> Added Frequency Code

LeetCode/permutationInString.cpp, LeetCode/removeAlloccOfString.cpp, LeetCode/validPalindrome.cpp
Strings Leetcode pRoblem 
Add HacktobeFestAccepted Label pls
Thank You
=> Leetcode Strings Problem

CoinChangeWays.cpp, DFS of Graph.cpp, Detect Cycle in Diagraph using DFS.cpp, Linked List Basics/Insert in a Sorted List.cpp, LongestCommonSubstring.cpp, MinmumCoinChage.cpp, Topological sort using DFS.cpp
I have created this issue plz accept...
=> Detect Cycle in Diagraph using DFS.cpp

countdowntimer.py
This is a simple code in python for count down timer.
=> Count Down Timer Code in Python

stack_evaluation.c
Please review my code and accept my code under hactoberfest accepted.
=> Added a C program of Stack Evaluation

Generate Binary Numbers.cpp
I have created this issue #506.
Will plz assign me this issue...?
=> Generate Binary Numbers.cpp

switch statement java
=> switch statement in java week days example

Introsort.java
Please merge this program into yours
=> Introsort in Java

Patiencesort.java
Please Merge this program to yours
=> Patience Sort in Java

Tournamentsort.java
Please Merge this program to yours
=> Tournament Sort in Java

CocktailSort.java
Please merge this program to yours
=> Cocktail Sort in Java

PigeonSort.java
Please merge this program to yours
=> Pigeon Sort in Java

CycleSort.java
Please merge this program to yours
=> Cycle Sort in Java Language

Island_dfs.java
Added Myself please accept my PR
=> Izroth404 Added DFS Solution to Island Problem 

Nth_Catalan_Number.java, kadanes_algorithm.java
Added nth-catalan number using dynamic programming
=> Izroth404 patch 2

difference_between_OddLevel_EvenLevel_BinaryTree.java
Created Odd and Even level in a binary tree
=> Izroth404 patch 3 1

Evaluation of Postfix Expression.cpp, Get min at pop.cpp, Remove repeated digits in a given number.cpp
I have created this issue #544.
Plz accept my request and assign me this issue...
=> Evaluation of Postfix Expression.cpp

C++/Sudoku.cpp
This is a basic 9x9 sudoku solving program using backtracking.
=> Adding sudoku solver

LeetCode/283. Move Zeroes/README.md, LeetCode/283. Move Zeroes/move_zeroes.py
Please add my file to your repository with label hacktoberfest.
=> Hacktoberfest2022

LeetCode/Merge_K_Sorted_Lists.cpp
My Leetcode Solution for Merge K Sorted Linked Lists
=> Merge K Sorted Linked Lists

Trapping_Rain_water
my leetcode solution for trapping rain water
=> trapping rain water

Pairwise Consecutive Elements.cpp, Queue Reversal.cpp
I have created this issue #596.
Plz assign me this issue
=> Queue Reversal.cpp

Count Non-Leaf Nodes in Tree.cpp
I have created this issue #590.
Will you plz accept my request and assign me this issue...?
=> Count Non-Leaf Nodes in Tree.cpp

Intro to CICD.md
Add my blog file to your repository with label Hacktober Fest.
=> Hacktober Fest 2022

Introduction of Kubernetes.md
Please add my blog file to your repository with label HacktoberFest-2022
=> HacktoberFest-2022

DP question - Minimum Falling Path Sum
It is a DP question done using memoization technique. It is medium level question on LeetCode.
=> DP (Medium level LeetCode) - 931. Minimum Falling Path Sum

LeetCode/Level order traversal in spiral form.cpp, binary-tree/Left View of Binary Tree.cpp
I created this issue #610.
Can you plz assign it to me...?
=> Level order traversal in spiral form.cpp

Ansible.md
Add my Blog to your repository with the label Hacktoberfest
=> Hacktoberfest 2022

LeetCode/9. Palindrome Number/Solution.py
Added solution of leetcode problem number 9 (Palindrome number).
=> Solution.py

Left View of Binary Tree.cpp, Linked List Basics/Count Pairs whose sum is equal to X.cpp, Linked List Basics/Find N by K th node in Linked list.cpp, binary-tree/Determine if Two Trees are Identical.cpp
I have created this issue  #506.
Plz assign me this issue...
=> Count Pairs whose sum is equal to X.cpp

LeetCode/returnkeypad.cpp, LeetCode/subsetsofaray.cpp
=> return keypad leetcode added

Linked List Basics/Circular Linked List Traversal.cpp, Linked List Basics/Delete Middle of Linked List.cpp
I have created this issue #651.
Plz assign me this issue.
=> Circular Linked List Traversal.cpp

Linked List Basics/Check If Circular Linked List.cpp
I have created this issue #656.
Will you plz assign me this issue...?
=> Check If Circular Linked List.cpp

LeetCode/containerwithmostwater.cpp, LeetCode/firstmissinginteger.cpp
=> first missing positve integer 

Linked List Basics/Doubly linked list Insertion at given position.cpp
I have created this issue #679.
Plz assign...
=> Doubly linked list Insertion at given position.cpp

Linked List Basics/Detect Loop in linked list.cpp
I have created this issue #677.
Will you assign it to me...?
=> Detect Loop in linked list.cpp

LeetCode/Sort a stack.cpp, Linked List Basics/Delete without head point.cpp
I have created this issue #675.
Plz accept my request...
=> Delete without head point.cpp

Linked List Basics/Given a linked list of 0s, 1s and 2s, sort it.cpp
I have created this issue #708.
Plz assign...
=> Given a linked list of 0s, 1s and 2s, sort it.cpp

Linked List Basics/Finding middle element in a linked list.cpp, Linked List Basics/Implement Stack using Linked List.cpp
I have created this issue #704.
Plz assign...
=> Finding middle element in a linked list.cpp

Linked List Basics/Deletion and Reverse in Linked List .cpp
I have created this issue #702.
=> Deletion and Reverse in Linked List .cpp

Linked List Basics/Delete a Node in Single Linked List.cpp
I have created this issue #718.
Plz assign...
=> Delete a Node in Single Linked List.cpp

Linked List Basics/Implement Stack using Linked List.cpp, Linked List Basics/Linked List Matrix.cpp
I have created this issue #715.
Plz assign...
=> Implement Stack using Linked List.cpp

Calendar.c
I added A project-Calendar Of any Year In C
please take look at this MR/PR request and approve it with hacktoberfest2022 & hacktoberfest2022-accepted label .
Thanking You
Jayadip
=> Calendar Project In C

SpiralMatrix.java
Added a file that implements the spiral Matrix using java code
=> added implementation of spiral matrix

Climbing Stairs.java
This is a basic easy level problem on LeetCode solved using DP memoization concept.
=> Climbing Stairs.java

Delete the middle node of a LinkedList.java
This is a medium level LinkedList problem on LeetCode.
=> Delete the middle node of a LinkedList.java

Linked List Basics/Absolute List Sorting.cpp
I have created this issue #747.
=> Absolute List Sorting.cpp

Linked List Basics/Modify Linked List-1.cpp, Linked List Basics/Modular Node.cpp
I have created this issue #745.
=> Modify Linked List-1.cpp

Linked List Basics/Find the Sum of Last N nodes of the Linked List.cpp
I have created this issue #743.
=> Find Sum of Last N nodes of the Linked List.cpp

Find optimal cost to construct a binary search tree.java
The idea is simple – consider each key as a root and find an optimal solution by recursively finding the optimal cost of left and right subtree and add left and right child cost to the current node’s price (frequency of that key × level of that node). If the current node’s cost is optimal, update the result.
=> Find optimal cost to construct a binary search tree.java

Linked List Basics/Move all zeros to the front of the linked list.cpp
I have created this issue #762.
=> Move all zeros to the front of the linked list.cpp

C++/Quadratic Equation.cpp
This program accepts coefficients of a quadratic equation from the user and displays the roots (both real and complex roots depending upon the discriminant).
=> Created a C++ Program to Find All Roots of a Quadratic Equation

Linked List Basics/Identical Linked Lists.cpp
I have created this issue #757.
=> Identical Linked Lists.cpp

binary-tree/K distance from root.cpp
I have created this issue #767.
=> K distance from root.cpp

Python turtle programming.py
Simple Turtle programming to make Python interesting in Hactoberfest 2022
=> Simple python Turtle programming

LeetCode/100. Same Tree/Solution.java
=> added 100.Same Tree Problem

binary-tree/Maximum Node Level.cpp
I have created this issue #771.
=> Maximum Node Level.cpp

Queue using two Stacks.cpp, binary-tree/Max and min element in Binary Tree.cpp
I have created this issue #765.
=> Max and min element in Binary Tree.cpp

Queue Push & Pop.cpp
I have created this issue #781.
=> Queue Push & Pop.cpp

Matrices.java
added java code to implement matrices multiplication
=> implemented matrice multiplication

Java/nQueens.java
The n-queens puzzle is the problem of placing n queens on an n x n chessboard such that no two queens attack each other.
Given an integer n, return all distinct solutions to the n-queens puzzle. You may return the answer in any order.
Each solution contains a distinct board configuration of the n-queens' placement, where 'Q' and '.' both indicate a queen and an empty space, respectively.
=> n-queens leetcode hard problem

Count the number of subset with a given difference.cpp
I have created this issue #794.
=> Count number of subset with a given difference.cpp

Minimum Subset Sum Difference.cpp
I have created this issue #791.
=> Minimum Subset Sum Difference.cpp

Unbounded Knapsack.cpp
I have created this issue #802.
=> Unbounded Knapsack.cpp

LinkedList.java
implemented linked list using java code
=> added implementation of linked list

binary-tree/Odd even level difference.cpp
I have created this issue #812.
=> Odd even level difference.cpp

Immediate Smaller Element.cpp
I have created this issue #808.
=> Immediate Smaller Element.cpp

Linked List Basics/Print Linked List elements.cpp
I have created this issue #822.
=> Print Linked List elements.cpp

QueueUsingStack.java
Java program to implement Queue using two stacks with costly enQueue
=> implemented queue using stack data structure

Queue Operations.cpp
I have created this issue #824.
=> Queue Operations.cpp

rock_paper_scissors.c
added a c program for rock paper scissor
=> c program for rock paper scissor

Linked List Basics/Occurrence of an integer in a Linked List.cpp
I have created this issue #833.
=> Occurrence of an integer in a Linked List.cpp

Linked list
=> added a code

LeetCode/Two Sum II - Input Array is sorted.cpp
Solution for Leetcode problem no.167
=> Added Solution for Two Sum-II

Binary to Decimal
I added a code of conversion of binary to decimal
=> binary to decimal

Insertion
Specific Position in a Doubly Linked List in Java.
=> I added Insertion

index.html, style.css
ADDED SIGNUP LOGIN LANDING PAGE USING HTML AND CSS.
Please accept it under Hacktober Fest 2022 and do provide the labels.
=> SIGNUP LOGIN LANDING PAGE USING HTML AND CSS

Linked List Basics/Rotate a Linked List.cpp, Split a Circular Linked List into two halves.cpp
I have created this issue #840.
=> Rotate a Linked List.cpp

Aural-Converter/README.md, Aural-Converter/css/style.css, Aural-Converter/index.html, Aural-Converter/js/app.js, Aural-Converter/js/loader.js
Hello, Added the Aural PDF-to-Audio converter web-app. Please do review and merge it.
=> Added the Aural web-application.

DBMS
=> added info

Linked List Basics/Rotate doubly Linked List.cpp
I have created this issue #869.
=> Rotate doubly Linked List.cpp

C++/C++_program/binary_search_leetcode_problems/book_allocation_problem.cpp, C++/C++_program/binary_search_leetcode_problems/peak_in_a_mountain_array.cpp, C++/C++_program/number_based_programs/armstrong_number.cpp, C++/C++_program/number_based_programs/automorphic_number.cpp, C++/C++_program/number_based_programs/buzz_number.cpp, C++/C++_program/number_based_programs/happy_number.cpp, C++/C++_program/number_based_programs/palindrome_number.cpp, C++/C++_program/pattern_programs/pattern1.cpp, C++/C++_program/pattern_programs/pattern2.cpp, C++/C++_program/pattern_programs/pattern3.cpp, C++/C++_program/pattern_programs/pattern4.cpp, C++/C++_program/pattern_programs/pattern5.cpp, C++/C++_program/pattern_programs/pattern6.cpp, C++/C++_program/pattern_programs/pattern7.cpp, C++/C++_program/pattern_programs/pattern8.cpp, C++/C++_program/searching_algo/binary.cpp, C++/C++_program/searching_algo/linear.cpp
leetcode problem on binary search like book allocation problem and peak in a mountain array has been implemented in cpp
=> Leetcode problem on binary search

C++/C++_program/number_based_programs/armstrong_number.cpp, C++/C++_program/number_based_programs/automorphic_number.cpp, C++/C++_program/number_based_programs/buzz_number.cpp, C++/C++_program/number_based_programs/happy_number.cpp, C++/C++_program/number_based_programs/palindrome_number.cpp, C++/C++_program/searching_algo/binary.cpp, C++/C++_program/searching_algo/linear.cpp
implemented number based program in cpp like armstrong,buzz,palindrome etc
=> Number based

Reverse a linked list
I added a code of reverse a linked list in c++
=> Reverse a linked list

Tower_of_hanoi.cpp
=> tower_of_hanoi

QuickSort.cpp
=> Quick sort program

Array/Find_Pivot_Index.cpp
=> added code

book store management system.py
please merge this pr in your repo under hactoberfest 2022
=> book store management system python

BinarySearch.cpp
please accept my pull request and mark it as hacktoberfest accepted
=> implemented binary search

C++/Program To Rotate An Array in Anticlockwise direction.txt
Hello.
myself kratik.
I want to add a C++ program to rotate an array in anticlockwise direction. I am new to open source and looking forward to complete hacktoberfest by making this contribution.
Thank You,
#hactoberfest2022
=> Program To Rotate An Array in Anticlockwise direction.

C++/insertion_vector.cpp
=> insertion_vector.cpp

C++/STL C++/STL_LEC_1_Array_1.cpp, C++/STL C++/STL_LEC_1_Array_2.cpp, C++/STL C++/STL_LEC_1_Iterators_1.cpp, C++/STL C++/STL_LEC_1_vector_1.cpp, C++/STL C++/STL_LEC_1_vector_2.cpp, C++/STL C++/STL_LEC_2_Map_1.cpp, C++/STL C++/STL_LEC_2_PriorityQueue_1.cpp, C++/STL C++/STL_LEC_2_Questions_1.cpp, C++/STL C++/STL_LEC_2_Questions_2.cpp, C++/STL C++/STL_LEC_2_Set_1.cpp, C++/STL C++/STL_LEC_2_Stack_Queue_1.cpp, C++/STL C++/STL_LEC_2_dequeue_1.cpp, C++/STL C++/STL_LEC_2_list_1.cpp, C++/STL C++/STL_LEC_3_Algorithms_1.cpp, C++/STL C++/STL_LEC_3_Algorithms_2.cpp, C++/STL C++/STL_LEC_3_Algorithms_3.cpp, C++/STL C++/STL_LEC_3_Algorithms_4.cpp, C++/STL C++/STL_LEC_3_Algorithms_5.cpp, C++/STL C++/STL_LEC_3_Algorithms_6.cpp, C++/STL C++/STL_LEC_3_Algorithms_7.cpp, C++/STL C++/STL_LEC_3_Bitset_1.cpp, C++/STL C++/Striver_Lec_Code.cpp, LeetCode/1_Two_Sum.cpp, LeetCode/2_Remove_Duplicates_from_Sorted_Array.cpp, LeetCode/3_Remove_Element.cpp, LeetCode/4_Search_Insert_Position.cpp, LeetCode/5_Plus_One.cpp, LeetCode/6_Container_With_Most_Water.cpp, LeetCode/7_3Sum.cpp
Hello, I've updated the repo with standard template library codes and leetcode problem codes with comments. Please accept PR. Thank you.
=> Updated repo with new codes LC-STL

C++/countSort.cpp
implementation of count sort in c++
=> added countSort.cpp

Trapping Rainwater problem on Array
Solution of Trapping rainwater array problem with linear time complexity, please merge this under hactoberfest
Happy Hacking.
=> Mayank sharma17 patch 2

C++/DP-cherryPickup.cpp
=> cherry pickup in dp

Todo_List/app.js, Todo_List/index.html, Todo_List/style.css
created a todo list using HTML, CSS and JS which stores the data locally on the browser using local storage
=> create todo list

Symmetric matrix.c, sparse_matrix.c
=> Create Symmetric matrix.c

coinchange.cpp
A C++ algorithm code for the coin change.
=> coin change code uploaded

Tarjan's Algorithm
Solving most asked interview question in graph - Tarjan's Algorithm
=> Create Tarjan's Algorithm
